version: "3.8"

services:
  go-backend:
    container_name: go-backend
    build:
      context: .
      dockerfile: backend/build/Dockerfile
    tty: true
    ports:
      - "8080:8080"
    volumes:
     - ./backend/cmd:/go/src/github.com/Seiji-Ikeda32/go-todo-app/backend

