import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to todo-App
        </h1>

        <p className={styles.description}>
          ファイルは{' '}
          <code className={styles.code}>src/pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs/api-routes/introduction" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>APIモードのドキュメント</p>
          </a>
          <a href="https://nextjs.org/learn/basics/create-nextjs-app" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>reactのチュートリアル</p>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home
